### ISSUE TITLE
redis parallel health check fail for redis cluster

### ISSUE THREAD

**Issue by kashifmehmood1991** [bitnami/bitnami-docker-redis-cluster#22]
Redis parallel check fails for redis cluster . I am using below mention helm chart  https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster

**cluster info**
```
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:2
cluster_stats_messages_ping_sent:101
cluster_stats_messages_pong_sent:101
cluster_stats_messages_meet_sent:1
cluster_stats_messages_sent:203
cluster_stats_messages_ping_received:101
cluster_stats_messages_pong_received:101
cluster_stats_messages_received:202
```
 **info replication**
```
# Replication
role:master
connected_slaves:1
slave0:ip=*.*.16.125,port=6379,state=online,offset=196,lag=1
master_replid:ff55cecd642d89b74ccf4b1ecc892b38a24425bd
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:196
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:196
```

 **cluster nodes**
```
97c2ab7e8e0744ccc4633856e294f619c0d11caf *.*.16.125:6379@16379 slave 6c992fb391b5a83505319b5d2fe950cab2baef7e 0 1615215354000 3 connected
a512eec32dfba657d4204df4a970ea338ce594ac *.*.16.189:6379@16379 master - 0 1615215356798 2 connected 5461-10922
a10e116f6c1f18f9b166059677778ffde8a39e60 *.*.16.58:6379@16379 slave 300483be28c09c96d51a13454f4ccb88a9ad891e 0 1615215355796 1 connected
6c992fb391b5a83505319b5d2fe950cab2baef7e *.*.16.18:6379@16379 myself,master - 0 1615215356000 3 connected 10923-16383
300483be28c09c96d51a13454f4ccb88a9ad891e :0@0 master,noaddr - 1615215153077 1615215151169 1 disconnected 0-5460
9214647465ee9ca5fe187cd53de59de47d0be259 *.*.17.40:6379@16379 slave a512eec32dfba657d4204df4a970ea338ce594ac 0 1615215355000 2 connected
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:6
cluster_my_epoch:3
cluster_stats_messages_ping_sent:246
cluster_stats_messages_pong_sent:266
cluster_stats_messages_meet_sent:1
cluster_stats_messages_sent:513
cluster_stats_messages_ping_received:266
cluster_stats_messages_pong_received:247
cluster_stats_messages_received:513
```
**cluster slots**
```
1) 1) (integer) 5461
   2) (integer) 10922
   3) 1) "*.*.16.189"
      2) (integer) 6379
      3) "a512eec32dfba657d4204df4a970ea338ce594ac"
   4) 1) "*.*.17.40"
      2) (integer) 6379
      3) "9214647465ee9ca5fe187cd53de59de47d0be259"
2) 1) (integer) 10923
   2) (integer) 16383
   3) 1) "*.*.16.18"
      2) (integer) 6379
      3) "6c992fb391b5a83505319b5d2fe950cab2baef7e"
   4) 1) "*.*.16.125"
      2) (integer) 6379
      3) "97c2ab7e8e0744ccc4633856e294f619c0d11caf"
3) 1) (integer) 0
   2) (integer) 5460
   3) 1) ""
      2) (integer) 0
      3) "300483be28c09c96d51a13454f4ccb88a9ad891e"
   4) 1) "*.*.16.58"
      2) (integer) 6379
      3) "a10e116f6c1f18f9b166059677778ffde8a39e60"
```
**ERROR**
```
PS C:\artifacts\RedisHealthChecker_Parallel\RedisHealthChecker\bin> .\RedisHealthChecker.exe "**********@dev-rr-rediscl1-redis-cluster?ConnectTimeout=10000&IdleTimeOutSecs=5"
Running 10000 x 4 user parallel read/write tests on **********@dev-rr-rediscl1-redis-cluster?ConnectTimeout=10000&IdleTimeOutSecs=5....
System.AggregateException: One or more errors occurred. (CLUSTERDOWN Hash slot not served)
 ---> ServiceStack.Redis.RedisResponseException: CLUSTERDOWN Hash slot not served
   at ServiceStack.Redis.RedisNativeClient.ParseSingleLine(String r) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 962
   at ServiceStack.Redis.RedisNativeClient.ReadData() in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 934
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 616
   at ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 718
   at ServiceStack.Redis.RedisNativeClient.GetBytes(String key) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient.cs:line 572
   at ServiceStack.Redis.RedisNativeClient.Get(String key) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient.cs:line 543
   at ServiceStack.Redis.Generic.RedisTypedClient`1.GetValue(String key) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\Generic\RedisTypedClient.cs:line 194
   at RedisHealthChecker.Program.ReadWriteUser(PooledRedisClientManager manager, Int32 i) in e:\RedisHealthChecker\RedisHealthChecker\Program.cs:line 61
   at RedisHealthChecker.Program.<>c__DisplayClass0_0.<Main>b__2(Int32 i) in e:\RedisHealthChecker\RedisHealthChecker\Program.cs:line 37
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at RedisHealthChecker.Program.<>c__DisplayClass0_0.<Main>b__0() in e:\RedisHealthChecker\RedisHealthChecker\Program.cs:line 37
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

**Comment by carrodher** [comment]
Can you provide some steps to reproduce the issue or your deployment? Such as custom parameters, the error appears without any action or during an upgrade, etc. With the existing information and looking at the error log, I don't know how can we help you since it seems an issue related to Redis itself (as the application) I can't see anything related to the container image or the chart.
